version: "3.8"
services:
    db:
        image: postgres
        volumes: 
            - ./migrations.sql:/docker-entrypoint-initdb.d/migrations.sql
            - ../.postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: ysl*gzzjic4Taok
            POSTGRES_DB: voluntariado_ing
    proxy:
        image: nginx
        ports: 
            - "80:8080"
        volumes: 
            - ./nginx/reverse_proxy.conf:/etc/nginx/conf.d/default.conf
        networks: 
            - front
            - back
        depends_on:
            - db
    bff:
        build: ../bff/
        environment:
            VA_IP: 'volunteers'
            VA_PORT: 8080
            DA_IP: 'donations'
            DA_PORT: 8080
        restart: always
        networks: 
            - back
        depends_on:
            - db
    donations:
        build: ../donations-api/
        environment:
            DB_HOST: 'db'
            DB_NAME: 'voluntariado_ing'
            DB_USER: 'postgres'
            DB_PASS: 'ysl*gzzjic4Taok'
        restart: always
        networks: 
            - back
        depends_on:
            - db
    volunteers:
        build: ../volunteer_api/
        environment:
            DB_HOST: 'db'
            DB_NAME: 'voluntariado_ing'
            DB_USER: 'postgres'
            DB_PASS: 'ysl*gzzjic4Taok'
        restart: always
        networks: 
            - back
        depends_on:
            - db
    mailer:
        build: ../mailer-api/
        restart: always
        networks: 
            - back
        depends_on:
            - db
    web:
        build: ../web-donaciones/
        restart: always
        networks: 
            - front
networks: 
    front:
    back: