version: "3.8"
services:
    db:
        image: postgres
        volumes: 
            - ./migrations.sql:/docker-entrypoint-initdb.d/migrations.sql
            - ../.postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: ysl*gzzjic4Taok            
        networks: 
            - back
    proxy:
        image: nginx
        restart: always
        ports: 
            - "80:8080"
        volumes: 
            - ./nginx/reverse_proxy.conf:/etc/nginx/conf.d/default.conf
        networks: 
            - front
            - back
        depends_on:
            - db
    bff:
        build: ../bff/
        environment:
            VA_IP: 'volunteers'
            VA_PORT: 8080
            DA_IP: 'donations'
            DA_PORT: 8080
            REDIS_HOST: cache
            REDIS_PORT: 6379
        restart: always
        networks: 
            - back
        depends_on:
            - db
            - cache
    donations:
        build: ../donations-api/
        environment:
            DB_HOST: 'db'
            DB_NAME: 'voluntariado_ing'
            DB_USER: 'postgres'
            DB_PASS: 'ysl*gzzjic4Taok'
            DB_PORT: 5432
        restart: always
        networks: 
            - back
        depends_on:
            - db
    volunteers:
        build: ../volunteer_api/
        environment:
            DB_HOST: 'db'
            DB_NAME: 'voluntariado_ing'
            DB_USER: 'postgres'
            DB_PASS: 'ysl*gzzjic4Taok'
            DB_PORT: 5432
            REDIS_HOST: cache
            REDIS_PORT: 6379
        restart: always
        networks: 
            - back
        depends_on:
            - db
            - cache
    mailer:
        build: ../mailer-api/
        restart: always
        networks: 
            - back
        depends_on:
            - db
    web:
        build: ../web-donaciones/
        environment:
            API_DOMAIN: 'voluntariadoing.ucc.edu.ar/'
        restart: always
        networks: 
            - front
            - back 
    cache:
        image: redis:alpine
        volumes:
            - ../.redis-data:/data
        restart: always
        networks: 
            - back 
networks: 
    front:
    back: